name: rich_form_field
description: Rich text form field with toolbar, styling ranges, and HTML codec output.
version: 0.1.0
repository: https://github.com/Asion001/rich_form_field
issue_tracker: https://github.com/Asion001/rich_form_field/issues

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.38.9

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
