name: rich_form_field
description: Rich text form field with HTML output.
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.38.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
