name: rich_form_field
description: Rich text form field with toolbar, styling ranges, and HTML codec output.
version: 0.3.0
repository: https://github.com/Asion001/rich_form_field
issue_tracker: https://github.com/Asion001/rich_form_field/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"
